## 파이썬

Numpy, Pandas, Matplotlib

In [ ]:
넘파이(Numpy)
    대수, 행렬, 통계 등 수학 및 과학 연산을 위한 라이브러리
    ndarray라는 다차원 배열을 데이터로 나타내고 처리하는데 특화
    실행속도가 빠르고 짧고 간경한 코드 구현이 가능.
    외부 라이브러리임

In [ ]:
NumPy 배열과 파이썬 리스트의 차이
    파이썬 리스트는 배열에 실제 데이터의 주소가 담겨져있음
    이것으로 인해 서로 다른 데이터 타입을 리스트 요소로 넣을 수 있음
    반면 Numpy 배열은 실제 데이터가 배열에 들어 있음
    리스트는 데이터를 읽고 쓰기에 numpy 배열보다 2배의 시간이 걸림
    대량의 배열 연산 또는 행렬 연산에는 numpy가 유리함

In [ ]:
넘파이 배열
    넘파이는 다차원 배열을 지원
    한 가지 자료형 데이터를 요소로 갖음

벡터 > 매트릭스 > 텐서(3차원 이상)

In [ ]:
np.array(리스트)
넘파이 배열은 콤마(,) 없이 공백으로 데이터를 구분함.

In [ ]:
np.arange(시작 인덱스 :  끝 인덱스: 간격)

In [ ]:
넘파이 배열에 들어가는 자료형
    한 가지 데이터 타입으로 통일되어 처리됨
    큰 범위의 데이터 처리를 기준으로 바뀜
    문자열행으로 통일, 실수형으로 통일

In [ ]:
2차원 배열 생성
    2차원 배열은 핼렬(matrix)라고 함
가로중은 행(row), 세로줄은 열(column)

In [ ]:
3차원 이상의 배열은 tensor
배열의 차원과 크기 알아보기
    .ndim 차원을 알려줌
    shape 넘파이.shape

In [ ]:
.shape
1차원 요소수가 4개라서 
(4,) 1차원이 이렇게 표현 됨.


In [ ]:
넘파이 배열명.reshape(크기)

넘파이 연산
shape이 같다면 덧셈, 뺄셈, 곱셈, 나눗셈의 연산을 할 수 있다.
동일한 인덱스 끼리 알아서 연산
np.array() 일괄적으로 모든 요소에 적용 거눙 (식 등)

#### Numpy

In [2]:
import numpy as np
# (확인 코드)

In [5]:
np.__version__

'2.3.3'

In [ ]:
!pip install numpy
numpy는 list보다 속도가 빠르다

In [6]:
L = range(1000)
%timeit L2 = [i **2 for i in L] #% timeit 시간 측정 매직 키워드 

54.1 μs ± 12.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

# arr가 list보다 2배 정도 빠르다
# 차이만 확인

1.22 μs ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
alist = [1,2,3,4,5,6]

In [9]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [ ]:
#의도적으로 빈칸을 둘 경우
blist = [1,2,  ,4,5,6] # SyntaxError 발생


In [ ]:
ar1 = np.array(alist) # (.) 콤마가 살라짐
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
ar1.dtype
# 정수형 타입

dtype('int64')

In [13]:
ar2 = np.array([1.1, 2.2, 3.3])

In [15]:
print(ar2)

[1.1 2.2 3.3]


In [16]:
ar2.dtype

dtype('float64')

In [17]:
list_data = [1,2. , 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)


[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan,4]) # 확장 1차원
#none - 파이썬 입장, nan=null - 데이터의 입장

array([ 1.,  2., nan,  4.])

In [20]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [22]:
(1, 4)

(1, 4)

In [23]:
arr2 = np.array([[1, 2, 3, 4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [24]:
(1, 2, 3)

(1, 2, 3)

In [25]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [30]:
arr3 = arr2.reshape(2, -1, 3) # -1는 하나만

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [40]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [41]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [42]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
#다양한 인덱싱 슬라이스를 지원함

In [43]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [ ]:
#백터화 연산 (개인 복습 필요)

In [ ]:
# 2 * a + b
# a == 2
# b > 10 
(a == 2) & (b > 10) # and는 불가, & 벡터 연산

array([False,  True, False])

In [50]:
a = np.array([1,2,3])

a == 2

array([False,  True, False])

In [ ]:
배열의 인덱싱

다음의 결과는?

a = np.array({0,1,2,3,4})
print(a[2]) 2
print(a[-1]) 4

In [78]:
alist = [0,1,2], [3,4,5]
#0, 1, 5 출력
print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [79]:
l_list = [[0, 1, 2], [3, 4, 5]]
# 0, 1 슬라이싱 [0, 1]
# 4, 5 슬라이싱 [4, 5]
# 1, 4를 하나의 리스트에 담아서 보여주세요(슬라이싱?) [1, 4] 

In [72]:
alist[0][:2]

[0, 1]

In [71]:
alist[1][1:]

[4, 5]

In [ ]:
result = [alist[0][1],alist[alist[1][1]]]
result = 

([0, 1, 2], [3, 4, 5])

In [94]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
print(blist[0][0], blist[0][1], blist[1][2])
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5
0 1 5


In [99]:
blist[0, :2]

array([0, 1])

In [100]:
blist[-1,1: ]

array([4, 5])

In [101]:
blist[: ,1] # : 처음부터 끝까지 

array([1, 4])

In [7]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a[: ,1]

array([1, 5])

In [5]:
a[1, 1:]

array([5, 6, 7])

In [11]:
result = a[:, :2]
print(result)


[[0 1]
 [4 5]]


In [ ]:
# 산출물 미션
clist = np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
clist
# 슬라이싱 최소 3회
[행, 열]

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
clist[:, 1]

array([ 1,  6, 10])

In [14]:
clist[: ,2]

array([ 2,  7, 11])

In [33]:
clist[:, 2][clist[:, 2] >= 2]

array([ 2,  7, 11])

## 팬시 인덱싱(fancy indexing)
- 수치적 경우엔 1차원으로 뽑는 것일 뿐이고
- 원래 위치나 차원이 중요한 경우엔 슬라이싱을 뽑아냄

In [41]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [42]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [46]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
b[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [49]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [50]:
arr = np.array([1,2,3,4,5,6,7,8,])

In [51]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [52]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [ ]:
# 조건문 연산을 사용하여 홀수인 원소만 골라내기
arr[arr % 2 != 0]

array([1, 3, 5, 7])