## 파이썬

Numpy, Pandas, Matplotlib

In [ ]:
넘파이(Numpy)
    대수, 행렬, 통계 등 수학 및 과학 연산을 위한 라이브러리
    ndarray라는 다차원 배열을 데이터로 나타내고 처리하는데 특화
    실행속도가 빠르고 짧고 간경한 코드 구현이 가능.
    외부 라이브러리임

In [ ]:
NumPy 배열과 파이썬 리스트의 차이
    파이썬 리스트는 배열에 실제 데이터의 주소가 담겨져있음
    이것으로 인해 서로 다른 데이터 타입을 리스트 요소로 넣을 수 있음
    반면 Numpy 배열은 실제 데이터가 배열에 들어 있음
    리스트는 데이터를 읽고 쓰기에 numpy 배열보다 2배의 시간이 걸림
    대량의 배열 연산 또는 행렬 연산에는 numpy가 유리함

In [ ]:
넘파이 배열
    넘파이는 다차원 배열을 지원
    한 가지 자료형 데이터를 요소로 갖음

벡터 > 매트릭스 > 텐서(3차원 이상)

In [ ]:
np.array(리스트)
넘파이 배열은 콤마(,) 없이 공백으로 데이터를 구분함.

In [ ]:
np.arange(시작 인덱스 :  끝 인덱스: 간격)

In [ ]:
넘파이 배열에 들어가는 자료형
    한 가지 데이터 타입으로 통일되어 처리됨
    큰 범위의 데이터 처리를 기준으로 바뀜
    문자열행으로 통일, 실수형으로 통일

In [ ]:
2차원 배열 생성
    2차원 배열은 핼렬(matrix)라고 함
가로중은 행(row), 세로줄은 열(column)

In [ ]:
3차원 이상의 배열은 tensor
배열의 차원과 크기 알아보기
    .ndim 차원을 알려줌
    shape 넘파이.shape

In [ ]:
.shape
1차원 요소수가 4개라서 
(4,) 1차원이 이렇게 표현 됨.


In [ ]:
넘파이 배열명.reshape(크기)

넘파이 연산
shape이 같다면 덧셈, 뺄셈, 곱셈, 나눗셈의 연산을 할 수 있다.
동일한 인덱스 끼리 알아서 연산
np.array() 일괄적으로 모든 요소에 적용 거눙 (식 등)

#### Numpy

In [56]:
import numpy as np
# (확인 코드)

In [5]:
np.__version__

'2.3.3'

In [ ]:
!pip install numpy
numpy는 list보다 속도가 빠르다

In [6]:
L = range(1000)
%timeit L2 = [i **2 for i in L] #% timeit 시간 측정 매직 키워드 

54.1 μs ± 12.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

# arr가 list보다 2배 정도 빠르다
# 차이만 확인

1.22 μs ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
alist = [1,2,3,4,5,6]

In [9]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [ ]:
#의도적으로 빈칸을 둘 경우
blist = [1,2,  ,4,5,6] # SyntaxError 발생


In [ ]:
ar1 = np.array(alist) # (.) 콤마가 살라짐
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
ar1.dtype
# 정수형 타입

dtype('int64')

In [13]:
ar2 = np.array([1.1, 2.2, 3.3])

In [15]:
print(ar2)

[1.1 2.2 3.3]


In [16]:
ar2.dtype

dtype('float64')

In [17]:
list_data = [1,2. , 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)


[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan,4]) # 확장 1차원
#none - 파이썬 입장, nan=null - 데이터의 입장

array([ 1.,  2., nan,  4.])

In [20]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [22]:
(1, 4)

(1, 4)

In [23]:
arr2 = np.array([[1, 2, 3, 4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [24]:
(1, 2, 3)

(1, 2, 3)

In [25]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [30]:
arr3 = arr2.reshape(2, -1, 3) # -1는 하나만

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [40]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [41]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [42]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
#다양한 인덱싱 슬라이스를 지원함

In [43]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [ ]:
#백터화 연산 (개인 복습 필요)

In [ ]:
# 2 * a + b
# a == 2
# b > 10 
(a == 2) & (b > 10) # and는 불가, & 벡터 연산

array([False,  True, False])

In [50]:
a = np.array([1,2,3])

a == 2

array([False,  True, False])

In [ ]:
배열의 인덱싱

다음의 결과는?

a = np.array({0,1,2,3,4})
print(a[2]) 2
print(a[-1]) 4

In [78]:
alist = [0,1,2], [3,4,5]
#0, 1, 5 출력
print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [79]:
l_list = [[0, 1, 2], [3, 4, 5]]
# 0, 1 슬라이싱 [0, 1]
# 4, 5 슬라이싱 [4, 5]
# 1, 4를 하나의 리스트에 담아서 보여주세요(슬라이싱?) [1, 4] 

In [72]:
alist[0][:2]

[0, 1]

In [71]:
alist[1][1:]

[4, 5]

In [ ]:
result = [alist[0][1],alist[alist[1][1]]]
result = 

([0, 1, 2], [3, 4, 5])

In [94]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
print(blist[0][0], blist[0][1], blist[1][2])
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5
0 1 5


In [99]:
blist[0, :2]

array([0, 1])

In [100]:
blist[-1,1: ]

array([4, 5])

In [101]:
blist[: ,1] # : 처음부터 끝까지 

array([1, 4])

In [7]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a[: ,1]

array([1, 5])

In [5]:
a[1, 1:]

array([5, 6, 7])

In [11]:
result = a[:, :2]
print(result)


[[0 1]
 [4 5]]


In [ ]:
# 산출물 미션
clist = np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
clist
# 슬라이싱 최소 3회
[행, 열]

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
clist[:, 1]

array([ 1,  6, 10])

In [14]:
clist[: ,2]

array([ 2,  7, 11])

In [33]:
clist[:, 2][clist[:, 2] >= 2]

array([ 2,  7, 11])

## 팬시 인덱싱(fancy indexing)
- 수치적 경우엔 1차원으로 뽑는 것일 뿐이고
- 원래 위치나 차원이 중요한 경우엔 슬라이싱을 뽑아냄

In [41]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [42]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [46]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
b[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [49]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [50]:
arr = np.array([1,2,3,4,5,6,7,8,])

In [51]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [52]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [ ]:
# 조건문 연산을 사용하여 홀수인 원소만 골라내기
arr[arr % 2 != 0]

array([1, 3, 5, 7])

In [57]:
#정수 배열 인덱싱 방식
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33,
       33])

In [ ]:
#산출물 미션 ([0], [[2]])
a = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[:, [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [64]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
# 맨 아래 행을 위로 올리기
a[[2, 0, 1],: ]
#호출 순서를 바꾸면 됨..

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
data = np.array([1, 4, 9, 16])
#연산자

In [68]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [ ]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [70]:
np.sum(data)

np.int64(30)

In [71]:
np.mean(data)

np.float64(7.5)

In [72]:
np.std(data)

np.float64(5.678908345800274)

In [ ]:
#미션 

x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20])
# 배열에서 3의 배수를 찾아주세요
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
# 배열에서 3으로 나누어 떨어지고 4로 나누면 1이 남는 수는?

In [77]:
# 배열에서 3의 배수를 찾아주세요
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [78]:
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [82]:
# 배열에서 3으로 나누어 떨어지고 4로 나누면 1이 남는 수는?
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## pandas 

In [84]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 6.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/11.3 MB 8.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/11.3 MB 9.1 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/11.3 MB 8.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/11.3 MB 8.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.2/11.3 MB 8.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.8/11.3 MB 8.8 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.3 MB 8.9 MB/s eta 0:00:01
   ------------- -------------------------- 3.7/11.3 MB 9.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.2/11.3 MB 9.2 MB/s eta 0:00:01
   ---------------- ----------------------- 4.6/11.3 MB 9.2 MB/s eta 0:00:01
   ----------------- ---------------------- 5.0/11.3 MB 9.2 MB/s eta 0:00:01
   ---


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [88]:
import pandas as pd

In [ ]:
pandas 사이트
https://pandas.pydata.org/

데이터를 조작/분석하기 위한 라이브러리
다양한 데이터 분석 함수 제공
행과 열로 이루어진 데이터 객체를 만들고 다룰 수 있게 해줌

In [ ]:
데이터 프레임 만들기
이중 리스트나 딕셔너리로 만들 수 있다.

csv 데이터
외부 데이터를 저장할 때 utf8로 지정해야 한글이 깨지지 않음
데이터 파일의 이름을 적어줄 때 같은 폴더 안에 위치 하지 않는다면 경로까지 적어준다.

In [ ]:
데이터프레임명["컬럼명"].apply(함수명)

def add_cm(height):
    return str(height) + 'cm'

df3['키'] = df3['키']

In [2]:
import pandas as pd

In [25]:
df = pd.read_csv('heroes.csv') #오타로 인한 FileNotFoundError 주의
df 

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [26]:
pd.options.display.float_format = '{:.0f}'.format

In [27]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [28]:
df.info() # 결과값 object는 str(문자열)을 시사

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [29]:
df.describe() #큰 숫자가 영향을 많이 받음

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [ ]:
df.head() # .tail()은 뒤에 있는 데이터 ()에 숫자를 넣으면 출력값에 영향을 줌.

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [ ]:
#국적의 분포도가 보고 싶은 경우
df['국적'] #['']를 적으면 자동 추천해줌, 가능한 타이핑보단 컬럼 추천을 사용할 것

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [30]:
type(df['국적']) # 시리즈

pandas.core.series.Series

In [102]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [103]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [107]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [31]:
df.nlargest(7, '나이')

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [32]:
df.nlargest(7, '키') # 7은 순위까지 보겠다는 표현

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [33]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [34]:
df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [35]:
df.iloc, df.loc #i는 번호, loc는 숫자 기반으로 작동

(<pandas.core.indexing._iLocIndexer at 0x25fa1235400>,
 <pandas.core.indexing._LocIndexer at 0x25fa1235810>)

In [36]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [37]:
# df.iloc[행번호, 열번호]
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [38]:
df.iloc[[1,3,6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [39]:
df.iloc[:5,:3] #[행번호, 열번호]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [40]:
df.loc[2:5] #loc는 이름 기반이라서 포함 

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [41]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [42]:
df.loc[3:, '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [43]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [44]:
#특정 조건 만족하는 경우
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [45]:
#나이가 30초과면서 50미만
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [46]:
#키가 180이상인 레코드의 이름과 나이컬럼만 출력 = df.loc 사용 필요
df.loc[df['키'] >= 180,['이름', '나이','키']]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [179]:
df['전투력'] = 98

In [161]:
df['전투력'] = df['전투력'] -5

In [162]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [181]:
df.drop(columns=['전투력'], inplace=True) 
# 임시적 삭제 (원본적용 x)
# inplace = True 저장 (원본적용 o)

In [200]:
df

0   58
1   45
2   18
3   27
4   33
5   36
6   32
Name: 나이, dtype: float64

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [47]:
df['재산'].isnull() #결측치

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [48]:
df[df['재산'].isnull()] #결측치

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [49]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [50]:
df.dropna() #이것도 임시저장 (원본적용 x)

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [51]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [52]:
df['재산'].fillna(df['재산'].mean()) #평균값으로 채우기

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [53]:
df = df.fillna(method='ffill')
# 초기화의 경우 df = pd.read_csv('파일명')

C:\Users\EL06\AppData\Local\Temp\ipykernel_15160\1843012933.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')


In [54]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [57]:
df.iloc[5, 1] = np.nan
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [58]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# 나이의 평균값으로 결측치를 채워주세요!!!!

In [59]:
# df['나이'].mean() #평균값으로 채우기
df['나이'].fillna(df['나이'].mean())

0   58
1   45
2   18
3   27
4   33
5   36
6   32
Name: 나이, dtype: float64

In [226]:
df['나이'] = df['나이'].fillna(df['나이'].mean())

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      7 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 468.0+ bytes


In [14]:
df  #캡틴마블 나이 = '36' 결과값 완료

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [60]:
#함수를 구현해주세요 174 -> 174cm로 일괄 변환됩니다
def add_cm(heghit): ## (실습 시간 내에 처리 못함 복습 필요)
    return str(heghit) + 'cm' 

df['키'] = df['키'].apply(add_cm) #갱신
df

이름  나이     직업     국적      키             재산
0   아이언맨  58    CEO     미국  174cm 11500000000000
1     토르  45      신  아스가르드  190cm 11500000000000
2  스파이더맨  18   고등학생     미국  177cm            600
3   원더우먼  27     공주  데미스키라  178cm            600
4     헐크  33  핵물리학자     미국  270cm     1000000000
5   캡틴마블 NaN    파일럿     미국  170cm      340000000
6  블랙위도우  32    스파이    러시아  170cm       50000000

In [ ]:
#cm 삭제 코드 (수정 필요)
def add_cm(heghit): 
    return str(heghit) + 'cm' 

def remove_cm(b):
    part = b.replace('cmcm','')
    part_float = float(part)
    return str(part_float) + 'cm'

    return
df['키'] = df['키'].apply(remove_cm)
# df['키'] = df['키'].apply(lambda a: str(a) + 'cm') #갱신
df

ValueError: could not convert string to float: '174cm'

In [64]:
df.groupby('국적')['나이'].mean()

국적
데미스키라   27
러시아     32
미국      36
아스가르드   45
Name: 나이, dtype: float64