## 파이썬

Numpy, Pandas, Matplotlib

In [ ]:
넘파이(Numpy)
    대수, 행렬, 통계 등 수학 및 과학 연산을 위한 라이브러리
    ndarray라는 다차원 배열을 데이터로 나타내고 처리하는데 특화
    실행속도가 빠르고 짧고 간경한 코드 구현이 가능.
    외부 라이브러리임

In [ ]:
NumPy 배열과 파이썬 리스트의 차이
    파이썬 리스트는 배열에 실제 데이터의 주소가 담겨져있음
    이것으로 인해 서로 다른 데이터 타입을 리스트 요소로 넣을 수 있음
    반면 Numpy 배열은 실제 데이터가 배열에 들어 있음
    리스트는 데이터를 읽고 쓰기에 numpy 배열보다 2배의 시간이 걸림
    대량의 배열 연산 또는 행렬 연산에는 numpy가 유리함

In [ ]:
넘파이 배열
    넘파이는 다차원 배열을 지원
    한 가지 자료형 데이터를 요소로 갖음

벡터 > 매트릭스 > 텐서(3차원 이상)

In [ ]:
np.array(리스트)
넘파이 배열은 콤마(,) 없이 공백으로 데이터를 구분함.

In [ ]:
np.arange(시작 인덱스 :  끝 인덱스: 간격)

In [ ]:
넘파이 배열에 들어가는 자료형
    한 가지 데이터 타입으로 통일되어 처리됨
    큰 범위의 데이터 처리를 기준으로 바뀜
    문자열행으로 통일, 실수형으로 통일

In [ ]:
2차원 배열 생성
    2차원 배열은 핼렬(matrix)라고 함
가로중은 행(row), 세로줄은 열(column)

In [ ]:
3차원 이상의 배열은 tensor
배열의 차원과 크기 알아보기
    .ndim 차원을 알려줌
    shape 넘파이.shape

In [ ]:
.shape
1차원 요소수가 4개라서 
(4,) 1차원이 이렇게 표현 됨.


In [ ]:
넘파이 배열명.reshape(크기)

넘파이 연산
shape이 같다면 덧셈, 뺄셈, 곱셈, 나눗셈의 연산을 할 수 있다.
동일한 인덱스 끼리 알아서 연산
np.array() 일괄적으로 모든 요소에 적용 거눙 (식 등)

#### Numpy

In [4]:
import numpy as np
# (확인 코드)

In [5]:
np.__version__

'2.3.3'

In [ ]:
!pip install numpy
numpy는 list보다 속도가 빠르다

In [6]:
L = range(1000)
%timeit L2 = [i **2 for i in L] #% timeit 시간 측정 매직 키워드 

54.1 μs ± 12.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

# arr가 list보다 2배 정도 빠르다
# 차이만 확인

1.22 μs ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
alist = [1,2,3,4,5,6]

In [9]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [ ]:
#의도적으로 빈칸을 둘 경우
blist = [1,2,  ,4,5,6] # SyntaxError 발생


In [ ]:
ar1 = np.array(alist) # (.) 콤마가 살라짐
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
ar1.dtype
# 정수형 타입

dtype('int64')

In [13]:
ar2 = np.array([1.1, 2.2, 3.3])

In [15]:
print(ar2)

[1.1 2.2 3.3]


In [16]:
ar2.dtype

dtype('float64')

In [17]:
list_data = [1,2. , 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)


[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan,4]) # 확장 1차원
#none - 파이썬 입장, nan=null - 데이터의 입장

array([ 1.,  2., nan,  4.])

In [20]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [22]:
(1, 4)

(1, 4)

In [23]:
arr2 = np.array([[1, 2, 3, 4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [24]:
(1, 2, 3)

(1, 2, 3)

In [25]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [30]:
arr3 = arr2.reshape(2, -1, 3) # -1는 하나만

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [40]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [41]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [42]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
